name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '0 16 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_DAYS_OF_WEEK: true
          SHOW_LANGUAGE: true
          SHOW_LINES_OF_CODE: true
          SHOW_TOTAL_CODE_TIME: false
          SHOW_PROFILE_VIEWS: false
          SHOW_EDITORS: false
          SHOW_PROJECTS: false
          SHOW_OS: false
